CREATE DATABASE inlock_games_dbFirst_manha
USE inlock_games_dbFirst_manha

CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
	Nome VARCHAR (100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	Datalancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)

CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario),
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR (100) NOT NULL
)

INSERT INTO Estudio
VALUES (NEWID(),'Sbt')



INSERT INTO Jogo
VALUES (NEWID(),'666CC2F6-039D-41F9-898F-9BFD655471EA','God of War','JOGO MANEIRO!','2018-10-09',160),
       (NEWID(),'80109834-EF1C-4221-8687-3716D13D4C15','Elden Ring','JOGO MANEIRO!','2022-08-29',300)



INSERT INTO TiposUsuario
VALUES (NEWID(),'Administrador'),(NEWID(),'Comum')



INSERT INTO Usuario
VALUES (NEWID(),'A842CB36-EC8B-4D63-A2C9-AF403C8CF824','adm@adm.com','admin'),
       (NEWID(),'040F22A7-4E5E-45DF-8CF7-1813EC446EFE','comum@comum.com','comum')



SELECT * FROM Usuario
SELECT * FROM TiposUsuario
SELECT * FROM Jogo
SELECT * FROM Estudio